name: Preview fastgpt-admin in pr
on:
  pull_request_target:
  workflow_dispatch:

jobs:
  preview-fastgpt-pro-images:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-preview-buildx-${{ github.event.pull_request.head.sha }}
          restore-keys: |
            ${{ runner.os }}-preview-buildx-${{ github.event.pull_request.base.sha }}
            ${{ runner.os }}-preview-buildx-
            ${{ runner.os }}-buildx-

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALI_HUB_USERNAME }}
          password: ${{ secrets.ALI_HUB_PASSWORD }}

      - name: Set DOCKER_REPO_TAGGED based on PR number
        run: |
          echo "DOCKER_REPO_TAGGED=${{ secrets.ALI_IMAGE_NAME }}/fastgpt-pro-pr:${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Build and publish image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: projects/app/Dockerfile
          build-args: |
            name=app
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/fastgpt-pro
            org.opencontainers.image.description=fastgpt-pro image
          push: true
          tags: ${{ env.DOCKER_REPO_TAGGED }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: '@finleyge/github-tools'
        uses: FinleyGe/github-tools@0.0.1
        id: print-image-label
        if: success()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tool: issue-comment
          title: 'Preview Image:'
          body: |
            ```
            ${{ env.DOCKER_REPO_TAGGED }}
            ```
